# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='index2',
            field=models.IntegerField(default=999, verbose_name='\u5206\u7c7b\u7684\u6392\u5e8f'),
        ),
    ]
